services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/codeclash
      - PORT=3000
      - DB_HOST=${DB_HOST}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pgnetwork

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #TODO IMPORTANT return this when we want to containerise the front end for deployment

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pgnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASS}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - pgnetwork

  # judge0:
  #   image: judge0/judge0:latest
  #   ports:
  #     - "2358:2358"
  #   privileged: true
  #TODO IMPORTANT return this when we want to start implementing code execution


  redis:
    image: redis:8.6.3-alpine
    container_name: codeclash-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
      - ./backend/src/frameworks-drivers/config/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    restart: unless-stopped
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4:9.16
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - "${PGADMIN_PORT}:5151"
    volumes: 
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgnetwork

volumes:
  postgres_data:
  postgres_test_data:
  pgadmin_data:
  redis-data:
    driver: local

networks:
  pgnetwork:
  
